### PR TITLE
Fixes typo in Heaven::Jobs::Deployment.redis_lock_key

### PR DESCRIPTION
**Pull request by Parad0X**
@atmos not sure if that's the best way to fix this. ```script/cibuild``` passed.

### CODE REVIEW

**Comment by atmos** [comment]
Do you have an example stacktrace for what this is fixing?

**Comment by Parad0X** [comment]
There's no stack trace. I don't know if ```payload``` has been moved under ```deployment``` but as it is now this function always return guid.

```json
{
  "deployment": {
    "url": "https://api.github.com/repos/Parad0X/heaven/deployments/1",
    "id": 1,
    "sha": "~",
    "ref": "master",
    "task": "deploy",
    "payload": {
      "name": "heaven",
      "hosts": "",
      "notify": {
        "room": "devs",
        "user": "Andrei Shevtsov",
        "adapter": "hipchat",
        "message_thread": "unknown"
      },
    },
    ...
}
```

**Comment by atmos** [comment]
Yeah, we moved them in october, https://developer.github.com/changes/2014-10-21-deployment-webhook-payload-changes/

I'll take a look. I don't use locking personally so it doesn't surprise me that it's broken. :smiley:

**Comment by Parad0X** [comment]
And I was very surprised when I saw to deploys running at the same time :cry: Thanks!

**Pull request closed without merging**
