### PR TITLE
Refactor towards a more maintainable test suite

### PR DESCRIPTION
**Pull request by dblandin**
A few goals were in mind during the development of this branch:

 - Fix up the `pending` specs
 - Return more intuitive status codes from the controllers
 - Pass around hashes instead of JSON strings when possible
 - Allow for easier addition of new request specs
 - Make sure the end-to-end deployment request spec works
 - Improve the organization of spec helpers

I'm hoping that maintaining a healthy suite of specs will be easier with the changes in this PR.

### CODE REVIEW

**Comment by dblandin** [comment]
@atmos Any thoughts on this PR?

**Comment by atmos** [comment]
Can you make me a collab on your repo? I got it down to 1 test failure.

**Comment by dblandin** [comment]
Done! Is there a way to reveal status of the CI builds here? Are they running on Travis? CircleCI?

**Comment by atmos** [comment]
I broke most of my CI stuff when we were testing oauth application policies unfortunately. I think we'd need to move this to an org to get everything working properly.

**Comment by atmos** [comment]
> Pass around hashes instead of JSON strings when possible

Are there any drawbacks to passing around JSON hashes to stuff like the `self.perform` methods vs strings that can be passed in/out and parsed?

**Comment by dblandin** [comment]
No, I don't believe so. `Resque` is using a `JsonCoder` behind the scenes so it's even re-encoding the JSON strings we pass in. Heaven shouldn't need to parse in and out of JSON strings. Using hashes would allow for more flexibility and would improve the readability of our specs.

[Resque queue instantiation](https://github.com/resque/resque/blob/8a8fd83f1f32755734f0068d9f211aeb2fda1f9e/lib/resque.rb#L85-L87)

```ruby
# lib/resque.rb#L85-L87
@queues = Hash.new do |h, name|
  h[name] = Resque::Queue.new(name, config.redis, coder)
end
```

[Default coder is JsonCoder](https://github.com/resque/resque/blob/8a8fd83f1f32755734f0068d9f211aeb2fda1f9e/lib/resque.rb#L103-L105)
```ruby
# lib/resque.rb#L103-L105
def coder
  @coder ||= JsonCoder.new
end
```

[Pushing to the queue](https://github.com/resque/resque/blob/master/lib/resque/queue.rb#L34-L38)
```ruby
# lib/resque/queue.rb#L34-L38
encoded_object = encode(object)
```

[JSON encoding](https://github.com/resque/resque/blob/8a8fd83f1f32755734f0068d9f211aeb2fda1f9e/lib/resque/json_coder.rb#L22-L23)
```ruby
# lib/resque/json_coder.rb#L22-L23
def encode(object)
  JSON.dump object
```

[Inline encoding and decoding](https://github.com/resque/resque/blob/8a8fd83f1f32755734f0068d9f211aeb2fda1f9e/lib/resque/job.rb#L63)
```ruby
# lib/resque/job.rb#L63
payload = {'class' => klass, 'args' => coder.decode(coder.encode(args))}
```

**Comment by atmos** [comment]
Right on. If we can get the tests passing I can roll this out to my installs and ensure it's still working as expected.

**Comment by dblandin** [comment]
Sweet. `script/cibuild` should be green now.

**Comment by dblandin** [comment]
Awesome :+1:

**Pull request merged**
